org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

minecraft_version = 1.20.1
minecraft_version_range = [1.20.1]
forge_version = 47.4.21
forge_version_range = [47,)
loader_version_range = [47,)

mapping_channel = parchment
mapping_version = 2023.09.03-1.20.1

mod_id = notjustspoiled
mod_name = Not Just Spoiled
mod_logo = notjustspoiled.png
mod_license = All Rights Reserved
mod_version = 0.4.1
mod_group_id = net.therealvoin.notjustspoiled
mod_authors = TheRealVoin
mod_url = https://modrinth.com/mod/not-just-spoiled
mod_issues_url = https://github.com/TheRealVoin/NotJustSpoiled/issues
mod_description = A modern food spoilage mod that enhances food management for a more immersive survival experience

FULLY_COMPATIBLE_MODS=
alexs_caves_version = 2.0.2
alexs_delight_version = 1.5
alexs_mobs_version = 1.22.9
deeper_and_darker_version = 1.3.3
dungeons_and_taverns_version = 3.0.3
dungeons_plus_version = 1.5.0
ends_delight_version = 2.6
genetic_animals_version = 0.11.12
oceans_delight_version = 1.0.2
ribbits_version = 3.0.5
simple_delights_recooked = 1.0.0
simple_farming_version = 2.2.6
survival_instinct_version = 1.0.2
terralith_version = 2.5.4
tough_as_nails_version = 9.2.0.171
yungs_better_desert_temples_version = 3.0.3
yungs_better_dungeons_version = 4.0.4
yungs_better_jungle_temples = 2.0.5
yungs_better_nether_fortresses = 2.0.6
yungs_better_ocean_monuments = 3.0.4
yungs_better_strongholds_version = 4.0.3
yungs_better_witch_huts_version = 3.0.3
yungs_cave_biomes_version = 2.0.5
yungs_extras_version = 4.0.3

NOT_FULLY_COMPATIBLE_MODS=
BLOCK_ENTITIES_ONLY=
farmers_delight_version = 1.3.2